### ISSUE TITLE
noscript text for every other email address is getting vanished, somehow

### ISSUE THREAD

**Issue by skinofthesoul** [skinofthesoul/grav-plugin-antispam#1]
Here's a weird bug I found. It's not too problematic so it may be a while before I can get to the root of this.

All email addresses on a page are rendered into javascript mailto links as expected, and a simple "view source code" shows that all of them have the correct text in their noscript tag. While javascript is turned on, this is also the state of affairs in the DOM when I check it with the developer toolkit.

However, when I turn javascript off, the browser (both Chromium and Firefox so far) renders every odd link in between `<div>` tags instead of `<noscript>`, so it displays but with a line break before it, and every even link is still in `<noscript>` tags in the DOM that do not get displayed at all – regardless of what elements I put the links in or how much text there is between them (I've experimented a bit).

### Rendered page with javascript:
![screenshot-page-with-js](https://user-images.githubusercontent.com/16343870/55814616-31298900-5aef-11e9-9cfa-c358eb2b690c.jpg)

### Rendered page without javascript:
![screenshot-page-without-js](https://user-images.githubusercontent.com/16343870/55814618-31298900-5aef-11e9-812c-d348413adac2.jpg)

### Developer toolkit with javascript:
![screenshot-developer-toolkit-with-js](https://user-images.githubusercontent.com/16343870/55815092-0b50b400-5af0-11e9-81c9-0cf908273593.jpg)

### Developer toolkit without javascript:
![screenshot-developer-toolkit-no-js](https://user-images.githubusercontent.com/16343870/55815056-fd029800-5aef-11e9-9e9e-efcb49216e1d.jpg)

### Source code of first two email addresses:
![screenshot-source-code-first-two](https://user-images.githubusercontent.com/16343870/55814619-31298900-5aef-11e9-9f6c-8d0c8d0e5c1f.jpg)

This is pretty weird and I'm not sure where to start with that, so feel free to poke this with a stick yourself.

**Comment by skinofthesoul** [comment]
Update: all noscript texts show up correctly in lynx.
![screenshot-lynx](https://user-images.githubusercontent.com/16343870/55912914-b1c9b180-5be3-11e9-8f90-dc53ebab1be5.jpg)

**Comment by skinofthesoul** [comment]
Heh, I don't know why, but this seems to be fixed as of version 1.3! :-D

**Comment by pamtbaau** [comment]
If it has been fixed (intentionally or magically), you might consider removing it from the TODO on the README page. One user on the forum is being put off because of it.

[Best way to protect the Email address on webpage](https://discourse.getgrav.org/t/best-way-to-protect-the-email-address-on-webpage/17186/2)
> The Antispam plugin as they say has an “odd bug”

**Comment by skinofthesoul** [comment]
Oh whoopsie, I totally forgot about that! Thanks for reminding me, I'll update the README right away!
