### ISSUE TITLE
Target blank for mail addresses

### ISSUE THREAD

**Issue by MrJack91** [skinofthesoul/grav-plugin-antispam#10]
Hi :)

Could you add a target="_blank" to the mail address.

like:
`"document.write(\"<a href='mailto:\"+link+\"' target='_blank'>\"+".$string."+\"</a>\")\n" .`

Would be awesome for gmail users (and other web mail users).

Thanks for you work! It's nice!

**Comment by skinofthesoul** [comment]
Sorry I'm suuuuper busy right now, will check this out soon!

**Comment by skinofthesoul** [comment]
Hey there, thanks for the input! There are, as usual, pros and cons to setting `target="_blank"` so I made this an option in the plugin configuration. Should be available with v1.4.2 in a bit!
