### ISSUE TITLE
Strange string appearing on top of the html

### ISSUE THREAD

**Issue by christophdoering** [skinofthesoul/grav-plugin-antispam#11]
// Email obfuscator script 2.1 by Tim Williams, University of Arizona // Random encryption key feature by Andrew Moulden, Site Engineering Ltd // PHP version coded by Ross Killen, Celtic Productions Ltd // This code is freeware provided these six comment lines remain intact // A wizard to generate this code is at http://www.jottings.com/obfuscator/ // The PHP code may be obtained from http://www.celticproductions.net/ coded = "2knfdfJZnIJ2vu0v" key = "d76GhR2PM1Bvfk8r0USyICs_oLWpAVF.ixc3XDqtJHQ4N5wung@jT9K-mzYObelaEZ" shift=coded.length link="" for (i=0; i
"+link+"") . 

The above text is visible on every page

**Comment by skinofthesoul** [comment]
Hmm, can I take a look at this somewhere? Just from this I can't tell what might be going wrong. Do you have other plugins installed that change the output of your page in any way?

**Comment by christophdoering** [comment]
First of all, I would like to thank you for the answer. Unfortunately I have the page only locally. I hope the attached output source code helps.
[source.txt](https://github.com/skinofthesoul/grav-plugin-antispam/files/5904048/source.txt)

**Comment by skinofthesoul** [comment]
Oh right, that's easy! :-) You put an email address in the description metatag, and the script turned it into javascript code that should not go in a tag attribute. I suggest you write an actual *description* for that attribute, with no more than 160 characters, no formatting, and a succinct summary of what the page is about. No email address.

(Feel free to ask if you'd like me to explain this in German!)

**Comment by christophdoering** [comment]
Thank you so much!
