### ISSUE TITLE
Distorts anchor tag

### ISSUE THREAD

**Issue by madaboutbrighton** [skinofthesoul/grav-plugin-antispam#12]
Thanks for your plugin. However, there is a bug where an anchor tag becomes distroted. If i do this in my markdown content...

`[email me](mailto:hello@mysite.com "Email me at My Site")`

I would expect this...

`<a href="mailto:hello@mysite.com" title="Email me at My Site">email me</a>`

But i am getting this...

`<a href="mailto:hello@mysite.com">hello@mysite.com</a>`

This is on a local site, so i do not have a link for you to look at. But please let me know if you require any further information. 

Many thanks!

**Comment by skinofthesoul** [comment]
Hey there, thank you for letting me know! Frankly I think nobody who uses the plugin has ever added a title tag to a mailto link yet, and I definitely didn't think about this possibility when I wrote the regex that finds the links. This will need some thinking, and I'm not sure I can fit it in this week, but I have it on my list now!

**Comment by skinofthesoul** [comment]
fixed in v1.5 :-D

**Comment by madaboutbrighton** [comment]
Thank you for having a look at this. Your fix does now preserve the contents of the anchor tag. However, it still strips out the title attribute. This happens when using markdown and pure html. So both

`[email me](mailto:hello@mysite.com "Email me at My Site")`

and...

`<a href="mailto:hello@mysite.com" title="Email me at My Site">email me</a>`

become...

`<a href="mailto:hello@mysite.com">email me</a>`

When they shoud be...

`<a href="mailto:hello@mysite.com" title="Email me at My Site">email me</a>`

Let me know if you need any further info. Many thanks.
