### ISSUE TITLE
Undefinded index : target

### ISSUE THREAD

**Issue by utagawal** [skinofthesoul/grav-plugin-antispam#13]
When Antispam plugin is turned on we have this issue  on a page with a specific route :

 /htdocs/system/src/Grav/Common/Debugger.php(352): Whoops\Run->handleError(8, 'Undefined index...', ' /htdocs/system/...', 131) 
/htdocs/user/plugins/antispam/antispam.php(131): Grav\Common\Debugger->deprecatedErrorHandler(8, 'Undefined index...', ' /htdocs/system/...', 131, Array) 
 [internal function]: Grav\Plugin\AntispamPlugin->munge(Array) 
/htdocs/user/plugins/antispam/antispam.php(62): preg_replace_callback('`\\<a([^>]+)href...', Array, '<!DOCTYPE html>...') 
/htdocs/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\AntispamPlugin->onOutputGenerated(Object(RocketTheme\Toolbox\Event\Event), 'onOutputGenerat...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) 
/htdocs/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onOutputGenerat...', Object(RocketTheme\Toolbox\Event\Event)) 
/htdocs/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onOutputGenerat...', Object(RocketTheme\Toolbox\Event\Event)) 
/htdocs/system/src/Grav/Common/Grav.php(403): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onOutputGenerat...', Object(RocketTheme\Toolbox\Event\Event)) 
/htdocs/system/src/Grav/Common/Processors/RenderProcessor.php(38): Grav\Common\Grav->fireEvent('onOutputGenerat...') 
 /htdocs/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RenderProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) 

Grav ver : 1.6.31
Antispam plugin ver : 1.4.2

The page renders correctly when antispam plugin is turned off

**Comment by skinofthesoul** [comment]
Yes, I've noticed that myself already – I simply forgot to add new default settings for the new toggle. You can fix this problem very quickly by going to the Antispam plugin settings in Admin and clicking "save". And I will update the defaults asap!
