### ISSUE TITLE
Uncaught SyntaxError: '' string literal contains an unescaped line break

### ISSUE THREAD

**Issue by 01Kuzma** [skinofthesoul/grav-plugin-antispam#15]
Hi!
Getting this error after upgrade to latest version:
`Uncaught SyntaxError: '' string literal contains an unescaped line break`
Points to this code piece: 

    document.write("<a href='mailto:"+link+"' target='_blank' >"+'

And instead of email link I'm getting: `'+"") `

**Comment by skinofthesoul** [comment]
Hmm, where exactly are you seeing this error? It does seem to work okay for me. Can you upload a screenshot or maybe a link?

**Comment by 01Kuzma** [comment]
HI,
with `v1.4.2 ` there is no error, while after the upgrade this happens.
It's running on a production website, so I could enable it for this day only.
It's located (#) 
Beneath `El. paštas` string, you will see `'+"") `

**Comment by skinofthesoul** [comment]
Alright, I took a screenshot, you can switch it off again. What _exactly_ is your input string? Like, what is written in your Markdown?

**Comment by 01Kuzma** [comment]
Thank you,
in markdown it's:
`emailAddress: info@asfaltavimas.eu`

**Comment by skinofthesoul** [comment]
Hm! I have only ever checked the output with regular body text fields, but this looks like you're using an extra blueprint. Are you using a plugin or theme that provides these fields? They're not in a regular Grav setup.

**Comment by 01Kuzma** [comment]
Yes, I'm using [this](https://github.com/devlom/grav-theme-hola) theme. This blueprint comes from a contact page.
But what is weird with version `1.4.2` everything was working, once I make an upgrade to `1.5` the bug comes out :/

**Comment by skinofthesoul** [comment]
Alright, so I installed that theme and guess what? It still works… I'm quite stumped. Do you have any other plugins that might interfere with the page output? My best guess at this point is that something causes Antispam to go over the output twice, because there's a double `noscript` tag with a remnant of a link. Could you give me a list of all your extra plugins, maybe?

**Comment by 01Kuzma** [comment]
Thank you for your effort!
I'm so sorry, it was my mistake - a typo in my child theme, and what is weird it was working in a past so this wasn't observed.
The code with error:
```
   <a href="mailto:{{ header.emailAddress|replace({',': '<br>'}) }}">
      {{ header.emailAddress|replace({',': '<br>'}) }}
   </a>  
```

While it should be: `{{ header.emailAddress|replace({',': '<br>'}) }}`
