### ISSUE TITLE
Working also in twig templates?

### ISSUE THREAD

**Issue by fspin** [skinofthesoul/grav-plugin-antispam#19]
Hi, thanks for your work! I love the plugin.
I wonder how difficult could be to make it work with e-mails added directly on a twig template?

I'm sorry if this question was already addressed. I didn't find nothing about it :) 

Kind regards.

**Comment by skinofthesoul** [comment]
Hello there, glad you enjoy the plugin!

As for your question, well… have you tried it? :-) If you put an email address directly in a twig template, you should set `change_on_output` to `true`, and Antispam should encrypt it. Please let me know if that doesn't work!

**Comment by skinofthesoul** [comment]
I just tested it and in my installation it does work if you change the setting I mentioned. I'll update the README with that info. Thanks for your input!

**Comment by fspin** [comment]
It works, indeed! Thanks a lot for your quick answer! 🙈 I didn't understand what in meant that option. Now it seems so obvious! My bad.
