### ISSUE TITLE
reponsive image urls get altered

### ISSUE THREAD

**Issue by markusritschel** [skinofthesoul/grav-plugin-antispam#2]
Hi.
First, thanks for this great plugin! It really works well so far. However, I recently wanted to give responsive images a try: https://learn.getgrav.org/16/content/media#responsive-images.
The problem is now, since the images have names à la `myimage@2x.jpg`, they get recognized by the plugin as e-mail address as soon as my screen matches the resolution of the original file (here 2x). Therefore the url of that image gets altered/destroyed.
Is it possible to somhow exclude images or handle this problem in another way?
Any hints or ideas?

**Comment by skinofthesoul** [comment]
Hey there, I'm thrilled to know somebody is using it! And thank you for letting me know about the image thing – I still haven't gotten around to setting up responsive images yet…

Well, there are several ways to go about this. As I mention in the docs, the script only finds pretty "standard" email addresses, no fringe cases, it's a fairly simple `preg_replace` thing. I could add a "no .jpg at the end" rule, or no "@[1-9]x". Actually the latter seems to me to be a fairly good idea, although a domain "2x.com" seems to exist! But if somebody has an email address there and wants to use my plugin, well… I'll make a new patch then. ;-)

I'll put this in straight away, expect an update from GPM in a few hours or so.
