### ISSUE TITLE
Remove type and language attributes from script tag

### ISSUE THREAD

**Issue by sushidave** [skinofthesoul/grav-plugin-antispam#21]
The [Nu HTML checker of w3.org](https://validator.w3.org/nu/) returns the following warnings for a site that uses the Antispam plugin:

```
Warning: The type attribute is unnecessary for JavaScript resources.
From line 201, column 13; to line 201, column 65
i>E-Mail: <script type="text/javascript" language="javascript">↩// Em
```

```
Warning: The language attribute on the script element is obsolete. You can safely omit it.
From line 201, column 13; to line 201, column 65
i>E-Mail: <script type="text/javascript" language="javascript">↩// Em
```
It seems that these attributes can be removed from the plugin's code?

**Comment by skinofthesoul** [comment]
I wasn't aware of that, so thank you! Will be changed in the next release.

**Comment by sushidave** [comment]
@skinofthesoul Nu HTML checker is happy and me too :) Thanks a lot for the fix.
