### ISSUE TITLE
domain.solutions

### ISSUE THREAD

**Issue by alasdair-at-flasher** [skinofthesoul/grav-plugin-antispam#22]
I have an email mail@[domain].solutions which ends up as mail@[domain].soluti

I'm guessing it's a regex thing...I'll try and work it out from the plugin myself but you might be able to figure it out more quickly!

**Comment by skinofthesoul** [comment]
Hm, that's a little odd. I managed to replicate it, will look into what's happening.

**Comment by skinofthesoul** [comment]
Yeah you were right, my regex was too restrictive. Top level domains used to be reliably much shorter… It's fixed in the next update.

**Comment by alasdair-at-flasher** [comment]
Working perfectly. Thanks for the amazing response!
