### ISSUE TITLE
Query parameters stripped from links

### ISSUE THREAD

**Issue by aricooperdavis** [skinofthesoul/grav-plugin-antispam#23]
Excellent plugin, thanks for your hard work!

Currently if you add a query parameter to a link, as one might to turn a link into a button for example:

```markdown
[Email](mailto:test@testdomain.net?class=button)
```

Then the query gets stripped but not added to the resultant anchor attribute, so it's rendered as:

```html
<a href="mailto:test@testdomain.net">Email</a>
```

when it should be rendered as

```html
<a class="button" href="mailto:test@testdomain.net">Email</a>
```

Many thanks,
Ari

**Comment by skinofthesoul** [comment]
Hey there, I am _SUPER_ sorry for not replying to you earlier! The end-of-year-last-minute-projects extended into January this time. I'll check out the pull request now – will need a moment as I've never had one before.

Thank you very much for contributing!!

**Comment by aricooperdavis** [comment]
Don't worry at all, it's easy to get snowed under, thanks for the excellent plugin! :)
