### ISSUE TITLE
unclosed html-comment can cause problem

### ISSUE THREAD

**Issue by itxup** [skinofthesoul/grav-plugin-antispam#3]
I installed the antispam AND the minifyHtml-plugin in my grav instance and the emails weren't obfuscated nor displayed at all anymore. 

When I inspected the html sources the console said that there is an unexpected else-clause. In the script the html-comment from the original coder is opened but it never gets closed. As long as you don't minify HTML code there is no problem with that. But if you minify the html output, the complete if-clause is being igored by the interpreter because of the unclosed comment. I fixed it in my local code and added the closing tag, since then it  works like expected again when minifyHTML is being used too. Without minifyHTML there is no problem at all of course.

To reproduce: use any instance of grav, install both minifyHTML and antispam, activate both and try to put out an email-address. 

Thx a lot!

**Comment by skinofthesoul** [comment]
Hmmm, interesting. Thank you for letting me know!

I just checked it and as far as I can see, the comment *does* get closed in the original script, right before the `</script>` tag. So my guess would be that minifyHTML strips it out, even though it keeps the start tag? I do not know why though. I think it makes more sense to post an issue in that plugin's queue.

**Comment by skinofthesoul** [comment]
Ah wait, I'm sorry. Where in your local code did you add that tag to fix it…? As I said, it's already there…

**Comment by itxup** [comment]
I added it to user/plugins/antispam/antispam.php in line 111... 
wait a minute, now I see it too, there really is a closing tag at the end - but there's a bug in it, that's why it's stripped by minification and why I never found it in the source code. I added my closing comment-tag to the end of the code where the original one was, and commented the original closing comment tag out:

![image](https://user-images.githubusercontent.com/41574081/61436237-aac8e280-a93a-11e9-951f-73f4286cb433.png)

The slash at the beginning was breaking it. I checked if it still works and it seems to be ok now.

**Comment by skinofthesoul** [comment]
Hmmmm! I see. Well according to [this thread on StackOverflow](https://stackoverflow.com/questions/1507939/using-html-comment-tag-still-relevant-around-javascript-code), the html comment tags around inline javascript aren't really necessary anymore, except maybe in some fringe cases. (Does anybody still go for XHTML instead of HTML5?!)

So I think I will just take these out, that fixes the issue with minifyHTML and is reasonably unlikely to cause new ones. Thank you for your feedback!
