### ISSUE TITLE
Links to the Readme gives 404

### ISSUE THREAD

**Issue by ThosG** [skinofthesoul/grav-plugin-antispam#4]
The link presented via the Admin panel is 
`https://github.com/skinofthesoul/grav-plugin-antispam/blob/develop/README.md`
which gives 404

The correct link seems to be
`https://github.com/skinofthesoul/grav-plugin-antispam/blob/master/README.md`

The link is also wrong in the Grav Plugin Repository

**Comment by skinofthesoul** [comment]
Quite so, thank you for letting me know! It's fixed in v1.2.4, and the plugin repository should get the correct one with its next update.

**Comment by ThosG** [comment]
@skinofthesoul Thanks for letting me know. And thanks also for the plugin!
