### ISSUE TITLE
no encryption on graphical browser and code printed on top of the page

### ISSUE THREAD

**Issue by aerdanb** [skinofthesoul/grav-plugin-antispam#5]
Hi, I'm sorry but my English... it's very bad.
I installed your plugin via Admin plugin, copied

> user/plugins/antispam/antispam.yaml

to

>user/config/plugins/antispam.yaml

and set

> enable: true

but, in graphical browser the address is not encrypted and -also in grafical and text browser- the code of antispam.php, from line 106  to... I don't know, is print in

>\<body id="top" class="modular header-animated header-fixed sticky-footer"\>

the content of $txt and some code output.

Can you help me, please? Thank you very much.

**Comment by aerdanb** [comment]
Code from web developer tools:

<body id="top" class="modular header-animated header-fixed sticky-footer">// Email obfuscator script 2.1 by Tim Williams, University of Arizona
// Random encryption key feature by Andrew Moulden, Site Engineering Ltd
// PHP version coded by Ross Killen, Celtic Productions Ltd
// This code is freeware provided these six comment lines remain intact
// A wizard to generate this code is at http://www.jottings.com/obfuscator/
// The PHP code may be obtained from http://www.celticproductions.net


coded = "I@NChdr_qdrbxCbIdFIm"
 key = "UhlDVYZ-jHs52ftW7FuxOX_S0a6nzgdo9NmA8QqPipTEBre@LKcCyvJ4k1wMIRG.3b"
 shift=coded.length
 link=""
 for (i=0; i<coded.length; i++)="" {="" if="" (key.indexof(coded.charat(i))="=-1)" ltr="coded.charAt(i)" link="" +="(ltr)" }="" else="" shift+key.length)="" %="" key.length="" document.write("<a="" href="mailto:&quot;+link+&quot;">"+link+"")

<noscript>[email address is javascript encrypted]</noscript>" /&gt;

    <link rel="icon" type="image/png"
---

![2019-08-20_1566296636_screenshot](https://user-images.githubusercontent.com/12890691/63342175-1c85b900-c34b-11e9-810a-29bdc5eb5659.png)

screenshot 1: chromium Version 73.0.3683.75 (Developer Build) built on Debian 9.8,
  running on Debian 9.9 (64-bit);

![2019-08-20_1566296768_screenshot](https://user-images.githubusercontent.com/12890691/63342181-227b9a00-c34b-11e9-8c20-98c844ae1642.png)

screenshot 2: w3m version w3m/0.5.3+git20170102, options
  lang=en,m17n,image,color,ansi-color,mouse,gpm,menu,cookie,ssl,ssl-verify,external-uri-loader,w3mmailer,nntp,gopher,ipv6,alarm,mark,migemo

**Comment by skinofthesoul** [comment]
Hey there. From what you are showing here, I can't really tell what's going wrong. Do you have a site up that I could look at?

This bit here seems to be wrong: `[email address is javascript encrypted]" />` <-- that tag end should not be there. Do you have other plugins installed that might be interfering with this? Possibly a minification plugin or something like that? We've had an [issue with minifyHTML](https://github.com/skinofthesoul/grav-plugin-antispam/issues/3) before that was similar.

**Comment by skinofthesoul** [comment]
Hey, is this still relevant, or did you solve the problem?

**Comment by aerdanb** [comment]
Hi, sorry but I abandoned that project. Maybe I'll take it back and rewrite you.Thanks for your interest!-------- Messaggio originale --------Oggetto: Re: [skinofthesoul/grav-plugin-antispam] no encryption on graphical browser and code printed on top of the page (#5)Da: Anna A: skinofthesoul/grav-plugin-antispam CC: Andrea Borrone ,Author Hey, is this still relevant, or did you solve the problem?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/skinofthesoul/grav-plugin-antispam/issues/5?email_source=notifications\u0026email_token=ADCLEQZHKTF2YTGJK75KHBDQ2HQP5A5CNFSM4INUK3YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHS7NZI#issuecomment-568719077",
"url": "https://github.com/skinofthesoul/grav-plugin-antispam/issues/5?email_source=notifications\u0026email_token=ADCLEQZHKTF2YTGJK75KHBDQ2HQP5A5CNFSM4INUK3YKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHS7NZI#issuecomment-568719077",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by skinofthesoul** [comment]
That's alright, just open a new issue then :-)
