### ISSUE TITLE
Script breaks emails in icons

### ISSUE THREAD

**Issue by fm** [skinofthesoul/grav-plugin-antispam#6]
It seems that if I put my email in an icon, it breaks the icon's CSS and renders it un-clickable.
<img width="939" alt="Screen Shot 2019-11-26 at 3 32 27 PM" src="https://user-images.githubusercontent.com/3654256/69670512-16962700-1062-11ea-8a60-6789d035f260.png">
<img width="623" alt="Screen Shot 2019-11-26 at 3 32 38 PM" src="https://user-images.githubusercontent.com/3654256/69670513-172ebd80-1062-11ea-92ee-4198c6f0d2e1.png">

Not sure what would be the best way to mitigate this...

**Comment by skinofthesoul** [comment]
Hello Faisal,

I'm sorry I couldn't get back to you earlier, my life has been a mess for a bit.

Anyway, let's see if I understand this correctly: Your input on your Grav page is something like
`<a href="mailto:your@email.address"><i class="fa fa-envelope"></a>`
and the output seems to be only the icon with no link around it any more. Is that correct?

I just tried it myself and this seems to be the case. I'll have to dig around in the code for that… will get back to you soon!

**Comment by skinofthesoul** [comment]
It's fixed in v1.3, but it did make my regular expressions much more… *interesting*. Anyway let me know if you still have problems!
