### ISSUE TITLE
Script makes ld+json scripts not valid

### ISSUE THREAD

**Issue by boohboohdog** [skinofthesoul/grav-plugin-antispam#7]
Hi, TNX for great addon! But i have issue - when i put email adress in ld+json script it got encripted, that makes the schema not valid for Google.

**Comment by skinofthesoul** [comment]
… ah! That's a bugger. Hmmm… but if you are putting a plain email address in your code anyway, what is the point of using encryption in other places? Bots just read all of your source code, scanning for addresses.

Unless you have several email addresses and only one of them in the json, that would make sense. In this case, if you have the json script on a different page than all the other addresses, you can use the new "disable for specific pages" feature which I shall release as soon as I can make my new computer play nicely with Github (so like, tonight or something). Will that help?

**Comment by skinofthesoul** [comment]
Did not hear back from you, maybe [disabling Antispam for individual pages](https://github.com/skinofthesoul/grav-plugin-antispam/tree/v1.4#disable-for-individual-pages) helped you out already. Will close this now.
