### ISSUE TITLE
if a email is wrapped with <a href="mailto:"> the email will not be encrypted

### ISSUE THREAD

**Issue by matulkum** [skinofthesoul/grav-plugin-antispam#8]
If I put `[mail@mail.com](mailto:mail@mail.com)` I will get `document.write("<a href='mailto:"+link+"'>"+'mail@mail.com'+"</a>")`.

So it suppose to be `document.write("<a href='mailto:"+link+"'>"+link+"</a>")` instead.

**Comment by skinofthesoul** [comment]
Hello there, I'm sorry I left you waiting! Thank you for alerting me to this – I have just fixed the issue in v1.4. Should be available as an update in Grav within a few hours.
