### ISSUE TITLE
Deprecated error : Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by n-vs-m** [skinofthesoul/grav-plugin-antispam#9]
Hello, I'm getting this error when displaying page :
```
Deprecated: Array and string offset access syntax with curly braces is deprecated in /Users/nix/Sites/ressources.pingbase.net/user/plugins/antispam/antispam.php on line 91

Deprecated: Array and string offset access syntax with curly braces is deprecated in /Users/nix/Sites/ressources.pingbase.net/user/plugins/antispam/antispam.php on line 112

Deprecated: Array and string offset access syntax with curly braces is deprecated in /Users/nix/Sites/ressources.pingbase.net/user/plugins/antispam/antispam.php on line 114

Deprecated: Array and string offset access syntax with curly braces is deprecated in /Users/nix/Sites/ressources.pingbase.net/user/plugins/antispam/antispam.php on line 115

Deprecated: Array and string offset access syntax with curly braces is deprecated in /Users/nix/Sites/ressources.pingbase.net/user/plugins/antispam/antispam.php on line 119

Deprecated: Array and string offset access syntax with curly braces is deprecated in /Users/nix/Sites/ressources.pingbase.net/user/plugins/antispam/antispam.php on line 120
```
The error only happens once when first displaying this page after a cache clearing, but it is very visible.
Antispam v1.4 and Grav v1.6.28

**Comment by n-vs-m** [comment]
It seems to be a php 7.4 problem.
Changing the indexes call with braces for square brackets seems to work. For example:

https://github.com/skinofthesoul/grav-plugin-antispam/blob/bcd7695a1beddfcc596755345c3bf104d36ffba9/antispam.php#L91

to
`$nextchar = $inprogresskey[$ranpos];`

**Comment by skinofthesoul** [comment]
_**Excellent**_ catch!! I hadn't noticed that problem anywhere yet, but you are quite right, this obscure alternative array notation is deprecated as of PHP 7.4. (I didn't even realise it existed, that bit of code was not written by me.) Sorry it took me so long to fix, I'm in the middle of a major house move. Thanks for helping out!
